misc:
#  gpu_mode: True
  verbose: True
  save_interim: True
#  verbose_freq: 100

dir:
  input_root: /scratch2/zhawang/datasets/Brienz_TLS/2002_2011/ROI_2_0/raw_pcd
  output_root: /scratch2/zhawang/projects/deformation/DeformHD_local/output/Brienz_TLS/2002_2011/ROI_2_0/evaluation
#  input_root: /scratch2/zhawang/datasets/Brienz_TLS/2002_2011/ROI_7/raw_pcd
#  output_root: /scratch2/zhawang/projects/deformation/DeformHD_local/output/Brienz_TLS/2002_2011/ROI_7/evaluation


data:
  src_pcd_name: Brienz_TLS_ROI_2_200221_reg_xyzrgb.ply
  tgt_pcd_name: Brienz_TLS_ROI_2_201130_reg_xyzrgb.ply
#  src_pcd_name: Brienz_TLS_200221_ROI_7_xyzrgb.ply
#  tgt_pcd_name: Brienz_TLS_201130_ROI_7_xyzrgb.ply

parameter_setting:
  radius: 5      # radius (m) of crop bounding box
  icp_thres: 0.1    # icp threshold for estimating gt transformation
  refine: True      # filter outlier matches or not
  compute_hvr: True
  icp_refine_img: True
  save_visualization_comparison: True

visualization:
  visualize_offset: 5
  visualize_gt_registration: False
  visualize_correspondences: True
  use_sub_sampled_correspondences: False
  num_sub_sample: 200
#  visualize_methods_registration: True
#  visualize_corr_icp: False
  visualize_registration_quality_of_methods: True
