misc:
#  gpu_mode: True
  verbose: True
  save_interim: True
#  verbose_freq: 100

dir:
  input_root: /scratch2/zhawang/projects/deformation/DeformHD_local/data/Rockfall_Simulator/raw_pcd
  output_root: /scratch2/zhawang/projects/deformation/DeformHD_local/output/Rockfall_Simulator/deform_translation/evaluation/

data:
  src_pcd_name: epoch_1.ply
  tgt_pcd_name: epoch_2.ply

parameter_setting:
  radius: 0.05       # radius (m) of crop bounding box
  icp_thres: 0.01    # icp threshold for estimating gt transformation
  refine: True      # filter outlier matches or not
  compute_hvr: True
  icp_refine_img: True
  save_visualization_comparison: True

visualization:
  visualize_offset: 5
  visualize_gt_registration: False
  visualize_correspondences: True
  use_sub_sampled_correspondences: False
  num_sub_sample: 200
#  visualize_methods_registration: True
#  visualize_corr_icp: False
  visualize_registration_quality_of_methods: True
