misc:
#  gpu_mode: True
  verbose: True
  save_interim: True
#  verbose_freq: 100

dir:
  input_root: /scratch2/zhawang/projects/deformation/DeformHD_local/data/Brienz/ROI_2/raw_pcd/
  output_root: /scratch2/zhawang/projects/deformation/DeformHD_local/output/Brienz/ROI_2/evaluation/

data:
  src_pcd_name: Brienz_TLS_ROI_2_200221_reg_xyzrgb.ply
  tgt_pcd_name: Brienz_TLS_ROI_2_201130_reg_xyzrgb.ply
  #  ['pure_2d_displace_vector, c2f_displace_vector', 'c2f_sparse_displace_vector']
  displace_vector: c2f_displace_vector.txt


parameter_setting:
  radius: 5         # radius (m) of crop bounding box
  icp_thres: 0.1    # icp threshold for estimating gt transformation
  refine: True      # filter outlier matches or not
  compute_hvr: True
  icp_refine_img: True
  save_visualization_comparison: True

visualization:
  visualize_offset: 5
  visualize_refined_registration: True
  visualize_refined_correspondences: False
  use_sub_sampled_correspondences: True
  num_sub_sample: 100
