misc:
  verbose: True

path_name:
  input_root: '/scratch2/zhawang/projects/deformation/DeformHD_local/data/Rockfall_Simulator/'
  # c2f, pure_2d
  output_root: '/scratch2/zhawang/projects/deformation/DeformHD_local/output/Rockfall_Simulator/deform_translation/c2f/'

data:
  src_image: 'epoch_1.jpg'
  tgt_image: 'epoch_2.jpg'

method:
  image_size: [5120, 5120]
  crop_size: [1500, 1500]
  overlap_size: [750, 1000]
